---
server:
  port: 8888
security:
  basic:
    enabled: true  
  user:
    name: martini
    password: martini
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: true        
        git:
          #uri: file://D:/Projetos/PPMTool-Spring-Cloud-WorkSpace/PPMTool-Spring-Cloud-Config-Wa-Tolls 
          #uri: file://C:/Martini/Projects/PPMTool-Spring-Cloud-WorkSpace/PPMTool-Spring-Cloud-Config-Wa-Tolls
          uri: https://github.com/OsvaldoMartini/PPMTool-Spring-Cloud-Config-Wa-Tolls
          #username: uname
          #password: pass
          search-paths:
            - 'station*'
          repos:
            perf:
                pattern:
                    - "*/perf"
                #uri: file://D:/Projetos/PPMTool-Spring-Cloud-WorkSpace/PPMTool-Spring-Cloud-Config-Wa-Tolls-Perf 
                uri: file://C:/Martini/Projects/PPMTool-Spring-Cloud-WorkSpace/PPMTool-Spring-Cloud-Config-Wa-Tolls-Perf
                #uri: https://github.com/OsvaldoMartini/PPMTool-Spring-Cloud-Config-Wa-Tolls-Perf
                search-paths:
                    - 'station*'
