---
server:
  port: 8888
security:  basic:    enabled: true  
  user:    name: martini
    password: martini
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false        
        git:
          uri: https://github.com/OsvaldoMartini/PPMTool-Spring-Cloud-Config-Wa-Tolls
          #username: uname
          #password: pass
          search-paths:
            - 'station*'
          repos:
            perf:
                pattern:
                    - "*/perf"
                uri: https://github.com/OsvaldoMartini/PPMTool-Spring-Cloud-Config-Wa-Tolls-Perf
                search-paths:
                    - 'station*'